services:
  php:
    build:
      context: docker/php
    container_name: doctrine-check-php
    volumes:
      - ../:/code:cached
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/docker-wrs.ini
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal idekey=PHPSTORM"
      PHP_IDE_CONFIG: "serverName=DocDC"
